export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'
export const UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP'
export const START_UPDATE_TIMESTAMP = 'START_UPDATE_TIMESTAMP'
